[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="currentModelPackage" type="org.jdom2.Element" --]
[#-- @ftlvariable name="currentModelObject" type="org.jdom2.Element" --]
[#-- @ftlvariable name="currentModelReference" type="org.jdom2.Element" --]
[#-- @ftlvariable name="currentModelAttribute" type="org.jdom2.Element" --]
[#-- @ftlvariable name="var1" type="java.lang.String" --]
[#-- @ftlvariable name="var2" type="java.lang.String" --]
[#-- @ftlvariable name="var3" type="java.lang.String" --]
[#-- @ftlvariable name="var4" type="java.lang.String" --]
[#-- @ftlvariable name="var5" type="java.lang.String" --]
[#-- @ftlvariable name="metafactory" type="com.metafactory.api.IMetaFactoryTemplateEngineProxy" --]
[#-- @ftlvariable name="generator" type="com.metafactory.api.IMetaFactoryTemplateEngineProxy" --]
